name: Build and Push React Image to Google Cloud Platform
on:
  push:
    branches: [dev]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: react-image
      PROJECT_ID: test-mala-calc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login with GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
#          export_default_credentials: true​
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
      - name: Push Docker Image to Container Registry
        env:
          GIT_TAG: v5.0
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: calc-image
      PROJECT_ID: test-mala-calc
    steps:
# 0. Initialize Terraform environment
  - name: hashicorp/terraform
    id: terraform-init
    args: ['init']
#    dir: 'pink-p2/environments/dev'
# 1. Apply Terraform
  - name: hashicorp/terraform
    id: terraform-apply
    args: ['apply', '-auto-approve']
#    dir:  'pink-p2/environments/dev'
# temp